// eslint-disable-next-line no-sparse-arrays
export const Team = [
  {
    id: 1,
    name: 'Arsenal',
    image: require('./img/arsenal.png'),
    location: 'London (Holloway)',
    stadium: 'Emirates Stadium',
    capacity: 60704,
    manager: 'Unai Emery',
    captain: 'Pierre-Emerick Aubameyang',
    lat: 51.554929,
    lng: -0.108449,
  },
  {
    id: 5,
    name: 'Burnley',
    image: require('./img/burnley.png'),
    location: 'Burnley',
    stadium: 'Turf Moor',
    capacity: 21944,
    manager: 'Sean Dyche',
    captain: 'Ben Mee',
    lat: 53.789017,
    lng: -2.230187,
  },
  {
    id: 6,
    name: 'Chelsea',
    image: require('./img/chelsea.png'),
    location: 'London (Fulham)',
    stadium: 'Stamford Bridge',
    capacity: 41631,
    manager: 'Frank Lampard',
    captain: 'César Azpilicueta',
    lat: 51.481696,
    lng: -0.190957,
  },
  {
    id: 8,
    name: 'Everton',
    image: require('./img/everton.png'),
    location: 'Liverpool (Walton)',
    stadium: 'Goodison Park',
    capacity: 39221,
    manager: 'Marco Silva',
    captain: 'Séamus Coleman',
    lat: 53.438813,
    lng: -2.966331,
  },
  {
    id: 10,
    name: 'Liverpool',
    image: require('./img/liverpool.png'),
    location: 'Liverpool (Anfield)',
    stadium: 'Anfield',
    capacity: 54074,
    manager: 'Jürgen Klopp',
    captain: 'Jordan Henderson',
    lat: 53.430846,
    lng: -2.960844,
  },
  {
    id: 11,
    name: 'Manchester City',
    image: require('./img/manchester-city.png'),
    location: 'Manchester',
    stadium: 'City of Manchester Stadium',
    capacity: 55017,
    manager: 'Pep Guardiola',
    captain: 'David Silva',
    lat: 53.483176,
    lng: -2.200427,
  },
  {
    id: 12,
    name: 'Manchester United',
    image: require('./img/manchester-united.png'),
    location: 'Manchester',
    stadium: 'Old Trafford',
    capacity: 74879,
    manager: 'Ole Gunnar Solskjær',
    captain: 'Ashley Young',
    lat: 53.463077,
    lng: -2.291334,
  },
  {
    id: 13,
    name: 'Newcastle United',
    image: require('./img/newcastle-united.png'),
    location: 'Newcastle',
    stadium: 'St James Park',
    capacity: 52354,
    manager: 'Steve Bruce',
    captain: 'Jamaal Lascelles',
    lat: 54.975581,
    lng: -1.621661,
  },
  {
    id: 14,
    name: 'Norwich City',
    image: require('./img/norwich-city.png'),
    location: 'Norwich',
    stadium: 'Carrow Road',
    capacity: 27244,
    manager: 'Daniel Farke',
    captain: 'Grant Hanley',
    lat: 52.622219,
    lng: 1.309328,
  },
];
